<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="sif--PC" name="emaiablereport.report" tests="14" failures="0" timestamp="28 Aug 2018 07:52:43 GMT" time="26.578" errors="1">
  <testcase name="add_order" time="0.010" classname="emaiablereport.report">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at emaiablereport.report.add_order(report.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- add_order -->
  <testcase name="login_page" time="26.504" classname="emaiablereport.report"/>
  <testcase name="hold_unhold" time="0.001" classname="emaiablereport.report"/>
  <testcase name="todays_order" time="0.006" classname="emaiablereport.report"/>
  <testcase name="add_lead" time="0.025" classname="emaiablereport.report"/>
  <testcase name="feedback" time="0.002" classname="emaiablereport.report"/>
  <testcase name="live_feed" time="0.002" classname="emaiablereport.report"/>
  <testcase name="chart_report" time="0.002" classname="emaiablereport.report"/>
  <testcase name="order_history" time="0.005" classname="emaiablereport.report"/>
  <testcase name="wallet_transaction" time="0.003" classname="emaiablereport.report"/>
  <testcase name="esclation" time="0.001" classname="emaiablereport.report"/>
  <testcase name="api_configuration" time="0.009" classname="emaiablereport.report"/>
  <testcase name="wallet_reachage" time="0.001" classname="emaiablereport.report"/>
  <testcase name="user" time="0.007" classname="emaiablereport.report"/>
</testsuite> <!-- emaiablereport.report -->
